server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location /auth {
        proxy_pass http://backend:8080;
    }
    location /tournaments {
        proxy_pass http://backend:8080;
    }
    location /leagues {
        proxy_pass http://backend:8080;
    }
    location /users {
        proxy_pass http://backend:8080;
    }
}